<?php

namespace ContainerM7HYocS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_POLudMOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.POLudMO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.POLudMO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articlesRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
        ], [
            'articlesRepository' => 'App\\Repository\\ArticlesRepository',
        ]);
    }
}
