<?php

namespace ContainerM7HYocS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BWCWU0QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bWCWU0Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bWCWU0Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ArticlesController::delete' => ['privates', '.service_locator.0GoQWpx', 'get_ServiceLocator_0GoQWpxService', true],
            'App\\Controller\\ArticlesController::edit' => ['privates', '.service_locator.0GoQWpx', 'get_ServiceLocator_0GoQWpxService', true],
            'App\\Controller\\ArticlesController::index' => ['privates', '.service_locator.POLudMO', 'get_ServiceLocator_POLudMOService', true],
            'App\\Controller\\ArticlesController::show' => ['privates', '.service_locator.0GoQWpx', 'get_ServiceLocator_0GoQWpxService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.2H_CT8a', 'get_ServiceLocator_2HCT8aService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iTWUpOY', 'get_ServiceLocator_ITWUpOYService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ArticlesController:delete' => ['privates', '.service_locator.0GoQWpx', 'get_ServiceLocator_0GoQWpxService', true],
            'App\\Controller\\ArticlesController:edit' => ['privates', '.service_locator.0GoQWpx', 'get_ServiceLocator_0GoQWpxService', true],
            'App\\Controller\\ArticlesController:index' => ['privates', '.service_locator.POLudMO', 'get_ServiceLocator_POLudMOService', true],
            'App\\Controller\\ArticlesController:show' => ['privates', '.service_locator.0GoQWpx', 'get_ServiceLocator_0GoQWpxService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.2H_CT8a', 'get_ServiceLocator_2HCT8aService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iTWUpOY', 'get_ServiceLocator_ITWUpOYService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ArticlesController::delete' => '?',
            'App\\Controller\\ArticlesController::edit' => '?',
            'App\\Controller\\ArticlesController::index' => '?',
            'App\\Controller\\ArticlesController::show' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ArticlesController:delete' => '?',
            'App\\Controller\\ArticlesController:edit' => '?',
            'App\\Controller\\ArticlesController:index' => '?',
            'App\\Controller\\ArticlesController:show' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
