<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM7HYocS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM7HYocS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM7HYocS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM7HYocS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM7HYocS\App_KernelDevDebugContainer([
    'container.build_hash' => 'M7HYocS',
    'container.build_id' => 'cbb08125',
    'container.build_time' => 1611264185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM7HYocS');
