<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2eg3an\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2eg3an/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2eg3an.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2eg3an\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2eg3an\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2eg3an',
    'container.build_id' => '93d74c13',
    'container.build_time' => 1611653887,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2eg3an');
